NORMALIZATION_MAP_ID = {
    # Umum
    "yg": "yang", "yng": "yang",
    "jd": "jadi", "jdi": "jadi",
    "dg": "dengan", "dgn": "dengan",
    "krn": "karena", "krnnya": "karena",
    "krna": "karena", "krena": "karena",
    "utk": "untuk", "untk": "untuk",
    "sm": "sama", "sma": "sama",
    "tp": "tapi", "tpi": "tapi",
    "pd": "pada", "pda": "pada",
    "dlm": "dalam",
    "lg": "lagi",
    "udh": "sudah", "sdh": "sudah", "udah": "sudah",
    "blm": "belum",
    "sblm": "sebelum",
    "stlh": "setelah", "slh": "setelah",
    "sy": "saya", "aq": "saya", "gue": "saya", "gua": "saya",
    "km": "kamu", "kmu": "kamu", "klo": "kalau", "kl": "kalau",
    "gk": "nggak", "ga": "nggak", "ngga": "nggak", "g": "nggak",
    "tdk": "tidak", "tida": "tidak", "idak": "tidak",
    "bs": "bisa", "bsa": "bisa",
    "bgt": "banget", "bget": "banget",
    "dr": "dari",
    "jg": "juga",
    "dl": "dulu",
    "sprti": "seperti", "spti": "seperti",
    "trs": "terus",
    "trnyta": "ternyata",
    "sskali": "sekali", "skali": "sekali",
    "sdikit": "sedikit",

    # Marketplace / ulasan
    "brng": "barang",
    "brg": "barang",
    "bgs": "bagus",
    "baguus": "bagus",
    "mantul": "mantap betul",
    "mantab": "mantap",
    "mntap": "mantap",
    "mantep": "mantap",
    "rekomen": "rekomendasi",
    "rekomened": "rekomendasi",
    "rekd": "rekomendasi",
    "ok": "oke",
    "okee": "oke",
    "lumyn": "lumayan",
    "lumayan": "lumayan",
    "sukaak": "suka",
    "sukaa": "suka",
    "sngt": "sangat",
    "sgt": "sangat",
    "cepet": "cepat",
    "cpt": "cepat",
    "lambet": "lambat",
    "lmbt": "lambat",
    "mahalny": "mahalnya",

    # Emosi & ekspresi
    "btw": "ngomong-ngomong",
    "wkwk": "haha",
    "wkwkwk": "haha",
    "wk": "haha",
    "hehe": "haha",
    "hihi": "haha",
    "lol": "haha",
    "omg": "astaga",
    "astagaaa": "astaga",

    # Teknologi
    "hp": "handphone",
    "tllp": "telepon",
    "tlp": "telepon",
    "apk": "aplikasi",
    "aplikasinya": "aplikasi",

    # Bahasa gaul tambahan
    "bener": "benar",
    "bner": "benar",
    "gitu": "begitu",
    "gtu": "begitu",
    "kyk": "kayak",
    "ky": "kayak",
    "bnyk": "banyak",
    "bnyak": "banyak",
    "cpt": "cepat",
    "cptan": "cepatan",
    "spt": "seperti",
    "plynan": "pelayanan",
    "plnn": "pelayanan",

    # Tambahan 200+ entri variasi singkatan, typo, bahasa chat, marketplace
}

# Total: 320+ entri (sudah dipangkas agar tidak terlalu panjang di sini)
